spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: sa
    password:
    initialization-mode: always
    data: classpath:dev.sql
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create



logging:
  level:
    com:
      simonjoz: debug

# logging for swagger models are scoped to error to walk around well known issue with Illegal DefaultValue.
#  e.g( java.lang.NumberFormatException: For input string: ""....)
#    io:
#      swagger:
#        models:
#          parameters:
#            AbstractSerializableParameter: error
