server:
  port: 8080

spring:
  profiles:
    active: dev
  application:
    name: vet-clinic
    appointment-duration: 30  # value in minutes is required
  jpa:
    # https://github.com/spring-projects/spring-boot/issues/7107
    # https://stackoverflow.com/questions/30549489/what-is-this-spring-jpa-open-in-view-true-property-in-spring-boot
    # NOTE: turning it off may result in LazyInitializationException.
    open-in-view: false

